# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

apt_packages:
 - python-dev
r_binary_packages:
 - Rcpp
 - jsonlite

env:
 global:
  - CRAN=http://cran.rstudio.com
  - NOT_CRAN=true

before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

notifications:
  email:
    on_success: change
    on_failure: change
