// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// py_init
void py_init(std::string name, std::string code);
RcppExport SEXP PyR_py_init(SEXP nameSEXP, SEXP codeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type code(codeSEXP);
    py_init(name, code);
    return R_NilValue;
END_RCPP
}
// py_close
void py_close();
RcppExport SEXP PyR_py_close() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    py_close();
    return R_NilValue;
END_RCPP
}
// py_exec
RcppExport SEXP py_exec(std::string py_code, std::string start);
RcppExport SEXP PyR_py_exec(SEXP py_codeSEXP, SEXP startSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type py_code(py_codeSEXP);
    Rcpp::traits::input_parameter< std::string >::type start(startSEXP);
    __result = Rcpp::wrap(py_exec(py_code, start));
    return __result;
END_RCPP
}
// py_get
RcppExport SEXP py_get(std::string var_name);
RcppExport SEXP PyR_py_get(SEXP var_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type var_name(var_nameSEXP);
    __result = Rcpp::wrap(py_get(var_name));
    return __result;
END_RCPP
}
