# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

py_init <- function(name = "", code = "") {
    invisible(.Call('PyR_py_init', PACKAGE = 'PyR', name, code))
}

py_close <- function() {
    invisible(.Call('PyR_py_close', PACKAGE = 'PyR'))
}

#' Execute Python code and return results as a std::string.
#'
#' @param py_code std::string containing Python code.
#' @param start Execution mode.
#'   c("eval","file","single")
py_exec_code <- function(py_code, start = "single") {
    .Call('PyR_py_exec_code', PACKAGE = 'PyR', py_code, start)
}

py_get_type <- function(var_name) {
    .Call('PyR_py_get_type', PACKAGE = 'PyR', var_name)
}

py_get_var <- function(var_name) {
    .Call('PyR_py_get_var', PACKAGE = 'PyR', var_name)
}

